apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090 # The 'prometheus' service in docker-compose
    isDefault: true
    access: proxy
    editable: true
