apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: PROM_DS_UID
    url: http://prometheus:9090 # The 'prometheus' service in docker-compose
    isDefault: true
    access: proxy
    editable: true
    jsonData:
      timeInterval: '15s'
      httpMethod: 'POST'
