name: "feedback"
description: "개선 아이디어나 피드백을 공유해주세요"
labels: ["feedback", "개선"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 피드백 및 개선 제안
        더 나은 서비스를 위한 여러분의 소중한 의견을 기다립니다!


  - type: dropdown
    id: feedback_type
    attributes:
      label: "📋 피드백 유형"
      description: "어떤 종류의 피드백인가요?"
      options:
        - "UI/UX 개선"
        - "성능 개선"
        - "코드 구조 개선"
        - "문서 개선"
        - "새로운 기능 제안"
        - "보안 개선"
        - "접근성 개선"
        - "기타"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: "중요도"
      description: "이 개선사항의 중요도는 어느 정도인가요?"
      options:
        - "🔴 Very High (매우 중요)"
        - "🟠 High (중요)"
        - "🟡 Medium (보통)"
        - "🟢 Low (낮음)"
    validations:
      required: true

  - type: textarea
    id: current_situation
    attributes:
      label: "현재 상황"
      description: |
        현재 어떤 부분에서 개선이 필요하다고 생각하시나요?
      placeholder: |
        예시: 현재 사용자 프로필 페이지의 로딩 속도가 느려서 사용자 경험이 좋지 않습니다.
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: "개선 제안"
      description: |
        어떻게 개선하면 좋을지 구체적으로 제안해주세요.
      placeholder: |
        예시:
        - 이미지 lazy loading을 적용하여 초기 로딩 속도를 개선
        - 사용자 정보를 캐싱하여 반복적인 API 호출 최소화
        - 프로필 편집 폼을 더 직관적으로 재구성
    validations:
      required: true

  - type: textarea
    id: expected_benefits
    attributes:
      label: "기대 효과"
      description: |
        이 개선사항이 적용되면 어떤 효과를 기대할 수 있나요?
      placeholder: |
        예시:
        - 페이지 로딩 속도 50% 향상
        - 사용자 이탈률 감소
        - 코드 가독성 및 유지보수성 향상
    validations:
      required: true

  - type: textarea
    id: implementation_ideas
    attributes:
      label: "구현 아이디어"
      description: |
        구체적인 구현 방법이나 기술적 아이디어가 있다면 공유해주세요.
      placeholder: |
        예시:
        - React.lazy()와 Suspense를 활용한 코드 스플리팅
        - Redis를 이용한 캐싱 시스템 도입
        - TypeScript 마이그레이션으로 타입 안정성 확보

  - type: textarea
    id: references
    attributes:
      label: "참고 자료"
      description: |
        관련 문서, 기사, 예시 등이 있다면 링크를 공유해주세요.
      placeholder: |
        - https://web.dev/performance-best-practices/
        - 비슷한 기능을 구현한 다른 서비스 예시
        - 관련 라이브러리나 도구 추천

  - type: textarea
    id: mockups
    attributes:
      label: "목업/스크린샷"
      description: |
        UI/UX 개선과 관련된 피드백이라면 목업이나 참고 이미지를 첨부해주세요.
      placeholder: |
        여기에 파일을 드래그하거나 클릭하여 업로드하세요.

  - type: textarea
    id: additional_notes
    attributes:
      label: "추가 사항"
      description: |
        위에서 다루지 못한 추가적인 의견이나 제안사항이 있다면 자유롭게 작성해주세요.
      placeholder: |
        기타 의견이나 질문사항을 작성해주세요.

  - type: checkboxes
    id: terms
    attributes:
      label: "체크리스트"
      description: "제출하기 전에 아래 항목들을 확인해주세요"
      options:
        - label: "비슷한 피드백이 이미 제출되지 않았는지 확인했습니다"
          required: true
        - label: "구체적이고 실행 가능한 개선 제안을 작성했습니다"
          required: true
        - label: "이 피드백이 프로젝트에 도움이 될 것이라고 생각합니다"
          required: true