name: "function"
description: "🚀 새로운 기능을 제안하거나 추가 계획을 공유해주세요"
labels: ["🚀 feature", "enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 🚀 새로운 기능 제안
        새로운 기능에 대한 아이디어를 구체적으로 설명해주세요!

  - type: dropdown
    id: feature_type
    attributes:
      label: "📋 기능 유형"
      description: "어떤 종류의 기능인가요?"
      options:
        - "👤 사용자 기능"
        - "🔧 관리자 기능"
        - "📊 분석/통계 기능"
        - "🔒 보안 기능"
        - "📱 모바일 최적화"
        - "🌐 API 기능"
        - "🎨 UI/UX 기능"
        - "⚡ 성능 최적화"
        - "🔗 외부 연동"
        - "📝 기타"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: "⭐ 우선순위"
      description: "이 기능의 우선순위는 어느 정도인가요?"
      options:
        - "🔴 Critical (필수 기능)"
        - "🟠 High (중요한 기능)"
        - "🟡 Medium (유용한 기능)"
        - "🟢 Low (부가 기능)"
    validations:
      required: true

  - type: textarea
    id: problem_statement
    attributes:
      label: "❓ 해결하고자 하는 문제"
      description: |
        이 기능이 해결하고자 하는 문제나 니즈는 무엇인가요?
      placeholder: |
        예시: 현재 사용자들이 자신의 운동 기록을 체계적으로 관리할 수 있는 방법이 없어서
        지속적인 건강 관리에 어려움을 겪고 있습니다.
    validations:
      required: true

  - type: textarea
    id: target_users
    attributes:
      label: "🎯 대상 사용자"
      description: |
        이 기능을 주로 사용할 사용자는 누구인가요?
      placeholder: |
        예시:
        - 일반 사용자 (운동을 시작하려는 초보자)
        - 피트니스 애호가 (꾸준히 운동하는 사람들)
        - 헬스 트레이너 (고객 관리가 필요한 전문가)
    validations:
      required: true

  - type: textarea
    id: feature_description
    attributes:
      label: "📝 기능 상세 설명"
      description: |
        구현하고자 하는 기능을 구체적으로 설명해주세요.
      placeholder: |
        예시:
        - 운동 종목별 기록 입력 (세트수, 무게, 반복수)
        - 일별/주별/월별 운동 통계 조회
        - 개인 목표 설정 및 달성률 추적
        - 운동 루틴 템플릿 저장 및 공유
    validations:
      required: true

  - type: textarea
    id: user_stories
    attributes:
      label: "📖 사용자 스토리"
      description: |
        사용자가 이 기능을 어떻게 사용할지 시나리오를 작성해주세요.
      placeholder: |
        예시:
        1. 사용자가 운동 기록 페이지에 접속한다
        2. "새 운동 추가" 버튼을 클릭한다
        3. 운동 종목을 선택하고 세트별 기록을 입력한다
        4. 저장 버튼을 누르면 기록이 저장되고 통계에 반영된다
        5. 대시보드에서 자신의 진전을 시각적으로 확인할 수 있다
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: "✅ 완료 조건"
      description: |
        이 기능이 완성되었다고 볼 수 있는 조건들을 나열해주세요.
      placeholder: |
        예시:
        - [ ] 운동 기록 입력 폼이 정상적으로 동작한다
        - [ ] 입력된 데이터가 데이터베이스에 저장된다
        - [ ] 통계 차트가 실시간으로 업데이트된다
        - [ ] 모바일에서도 원활하게 사용할 수 있다
        - [ ] 데이터를 CSV로 내보낼 수 있다

  - type: textarea
    id: technical_requirements
    attributes:
      label: "🔧 기술적 요구사항"
      description: |
        개발에 필요한 기술적 요구사항이나 제약사항이 있다면 작성해주세요.
      placeholder: |
        예시:
        - 차트 라이브러리: Chart.js 또는 D3.js 사용
        - 데이터베이스: PostgreSQL 테이블 설계 필요
        - API: RESTful API 엔드포인트 3개 추가
        - 인증: 로그인한 사용자만 접근 가능
        - 성능: 1000개 기록까지 원활한 렌더링

  - type: textarea
    id: mockups
    attributes:
      label: "🎨 목업/와이어프레임"
      description: |
        기능의 UI/UX를 설명할 수 있는 목업이나 와이어프레임을 첨부해주세요.
      placeholder: |
        여기에 파일을 드래그하거나 클릭하여 업로드하세요.

  - type: textarea
    id: references
    attributes:
      label: "📚 참고 자료"
      description: |
        비슷한 기능을 구현한 다른 서비스나 참고할 만한 자료가 있다면 공유해주세요.
      placeholder: |
        예시:
        - MyFitnessPal의 운동 기록 기능
        - Strava의 운동 통계 차트
        - https://example.com/fitness-app-ui-inspiration

  - type: input
    id: estimated_effort
    attributes:
      label: "⏱️ 예상 개발 시간"
      description: "이 기능 개발에 필요한 예상 시간을 입력해주세요"
      placeholder: "예시: 2-3주, 1개월, 단기간 등"

  - type: textarea
    id: additional_notes
    attributes:
      label: "📝 추가 사항"
      description: |
        위에서 다루지 못한 추가적인 정보나 고려사항이 있다면 작성해주세요.
      placeholder: |
        - 다른 기능과의 연관성
        - 마케팅적 고려사항
        - 장기적 확장 계획 등

  - type: checkboxes
    id: terms
    attributes:
      label: "✅ 체크리스트"
      description: "제출하기 전에 아래 항목들을 확인해주세요"
      options:
        - label: "비슷한 기능 요청이 이미 존재하지 않는지 확인했습니다"
          required: true
        - label: "사용자 관점에서 구체적인 니즈를 설명했습니다"
          required: true
        - label: "기능의 범위와 완료 조건을 명확히 했습니다"
          required: true