global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # Evaluate rules every 15 seconds
  scrape_timeout: 10s # Scrape timeout

  external_labels:
    monitor: 'livelink-monitor'
    environment: 'production'

scrape_configs:
  # Node.js Application Metrics
  - job_name: 'nodejs-app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['app:3000'] # The 'app' service in docker-compose, port 3000
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'process_.*|nodejs_.*|http_.*'
        action: keep

  # Prometheus Self-Monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # MongoDB Exporter (optional - if you add mongodb-exporter later)
  # - job_name: 'mongodb'
  #   static_configs:
  #     - targets: ['mongodb-exporter:9216']

  # Redis Exporter (optional - if you add redis-exporter later)
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis-exporter:9121']
