export enum SupportCategory {
  BOOKING_SITE_ERROR = 'BOOKING_SITE_ERROR',
  ACCOUNT_SETTINGS = 'ACCOUNT_SETTINGS',
  NOTIFICATION_ISSUE = 'NOTIFICATION_ISSUE',
  SETTINGS_INQUIRY = 'SETTINGS_INQUIRY',
  CONCERT_INFO_ERROR = 'CONCERT_INFO_ERROR',
  LOGIN_ERROR = 'LOGIN_ERROR',
  OTHER = 'OTHER',
}

export enum InquiryStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  ANSWERED = 'ANSWERED',
  CLOSED = 'CLOSED',
}

export enum Priority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
}
