// src/types/express.d.ts
import 'express';

declare global {
  namespace Express {
    interface Request {
      /**
       * Unique request ID for tracking and logging
       * Generated by requestIdMiddleware
       */
      id?: string;

      user?: {
        userId: string;
        email: string;
        username: string;
        profileImage?: string;
        loginTime: string;
      };
    }
  }
}
